name: "PR Testing"

on: [pull_request]

jobs:
  litmus:
    name: "Litmus: ${{ matrix.platform }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - debian-11
          - debian-12
          - ubuntu-20.04
          - ubuntu-2204
          - centos-7
          - centos-8
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Provision Test Environment
        run: bundle exec rake "litmus:provision[docker, ${{ matrix.platform }}]"

      - name: Install OpenVox Agent
        run: |
          bundle exec rake spec_prep
          bundle exec bolt task run openvox_bootstrap::install --targets all --inventory spec/fixtures/litmus_inventory.yaml

      - name: Install Module
        run: bundle exec rake "litmus:install_module"

      - name: Run Acceptance Tests
        run: bundle exec rake "litmus:acceptance:parallel"

      - name: Tear Down
        if: always()
        run: bundle exec rake "litmus:tear_down"